<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AutoConfigLib">
      <HintPath>..\..\AutoConfigLib\AutoConfigLib\bin\Debug\Mods\mod\AutoConfigLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\Mono.Cecil.Mdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\Mono.Cecil.Pdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\Mono.Cecil.Rocks.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Nat">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\Mono.Nat.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Backports">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\MonoMod.Backports.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Core">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\MonoMod.Core.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Iced">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\MonoMod.Iced.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.ILHelpers">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\MonoMod.ILHelpers.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>C:\Users\krizz\AppData\Roaming\Vintagestory\Lib\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(VINTAGE_STORY)/Mods/VSEssentials.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSCreativeMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSCreativeMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VINTAGE_STORY)/Lib/Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(VINTAGE_STORY)/Lib/0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VINTAGE_STORY)/VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(VINTAGE_STORY)/Lib/protobuf-net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="cairo-sharp">
      <HintPath>$(VINTAGE_STORY)/Lib/cairo-sharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Data.Sqlite">
      <HintPath>$(VINTAGE_STORY)/Lib/Microsoft.Data.Sqlite.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

<ItemGroup>
  <Content Include="modinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

<ItemGroup>
  <Folder Include="Attributes\Auto\UI\" />
  <Folder Include="Config\Auto\" />
</ItemGroup>

</Project>
