<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Path to your ModInfo file -->
		<ModInfoFile>modinfo.json</ModInfoFile>
	</PropertyGroup>

	<Target Name="ReadModInfo" BeforeTargets="BeforeBuild">

		<!-- Read mod id -->
		<JsonPeek ContentPath="$(ModInfoFile)" Query="$.modid">
			<Output TaskParameter="Result" PropertyName="ModIDFromJson" />
		</JsonPeek>
		
		<!-- Read mod name -->
		<JsonPeek ContentPath="$(ModInfoFile)" Query="$.name">
			<Output TaskParameter="Result" PropertyName="ModNameFromJson" />
		</JsonPeek>

		<!-- Read description -->
		<JsonPeek ContentPath="$(ModInfoFile)" Query="$.description">
			<Output TaskParameter="Result" PropertyName="DescriptionFromJson" />
		</JsonPeek>

		<!-- Read authors -->
		<JsonPeek ContentPath="$(ModInfoFile)" Query="$.authors[*]">
			<Output TaskParameter="Result" PropertyName="AuthorsFromJson" />
		</JsonPeek>

		<!-- Read version -->
		<JsonPeek ContentPath="$(ModInfoFile)" Query="$.version">
			<Output TaskParameter="Result" PropertyName="VersionFromJson" />
		</JsonPeek>

		<!-- Set all relevant properties -->
		<PropertyGroup>
			<ModID>$(ModIDFromJson)</ModID>
			<Title>$(ModNameFromJson)</Title>
			<Description>$(DescriptionFromJson)</Description>
			<Authors>$(AuthorsFromJson)</Authors>
			<Version>$(VersionFromJson)</Version>
			
			<HasInsanityLibDependency>*</HasInsanityLibDependency>
		</PropertyGroup>
	</Target>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		
		<!-- Package -->
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageOutputPath>bin\$(Configuration)</PackageOutputPath>
		
		<PackageId>VintageStory.$(MSBuildProjectName)</PackageId>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>True</IncludeSymbols>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PackageIcon>modicon.png</PackageIcon>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<Nullable>enable</Nullable>

		<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="VintageStory.AutoConfigLib" Version="1.0.0" />
		
		<ProjectReference Include="..\InsanityLib.Generators\InsanityLib.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\InsanityLib.Analyzers\InsanityLib.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\InsanityLib.Generators.Attributes\InsanityLib.Generators.Attributes.csproj" private="false" PrivateAssets="all"/>

		<None Include="..\InsanityLib.Generators\bin\$(Configuration)\InsanityLib.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="..\InsanityLib.Analyzers\bin\$(Configuration)\InsanityLib.Analyzers.dll" Pack="true" PackagePath="analyzers/dotnet/cs" visible="false" />
		<None Include="..\InsanityLib.Generators.Attributes\bin\$(Configuration)\InsanityLib.Generators.Attributes.dll" Pack="true" PackagePath="lib/netstandard2.0" visible="false" />
		<None Include="..\InsanityLib.Generators.Attributes\bin\$(Configuration)\InsanityLib.Generators.Attributes.xml" Pack="true" PackagePath="lib/netstandard2.0" visible="false" />
		
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="JsonPeek" Version="1.2.0" />
		<Reference Include="configlib">
			<HintPath>..\..\Dep\configlib_1.4.1\configlib.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="ImGui.NET">
			<HintPath>..\..\Dep\vsimgui_1.1.7\ImGui.NET.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="VSImGui">
			<HintPath>..\..\Dep\vsimgui_1.1.7\VSImGui.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="xlib">
			<HintPath>..\..\Dep\xlib_v0.8.16\xlib.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="VintagestoryAPI">
			<HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="VSSurvivalMod">
			<HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="VSEssentials">
			<HintPath>$(VINTAGE_STORY)/Mods/VSEssentials.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="VSCreativeMod">
			<HintPath>$(VINTAGE_STORY)/Mods/VSCreativeMod.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>$(VINTAGE_STORY)/Lib/Newtonsoft.Json.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(VINTAGE_STORY)/Lib/0Harmony.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="VintagestoryLib">
			<HintPath>$(VINTAGE_STORY)/VintagestoryLib.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="cairo-sharp">
			<HintPath>$(VINTAGE_STORY)/Lib/cairo-sharp.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	
	<ItemGroup>
		<CompilerVisibleProperty Include="ModID" />
		<CompilerVisibleProperty Include="HasInsanityLibDependency" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="modinfo.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>false</Pack>
		</Content>
		<Content Include="modicon.png;..\LICENSE.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</Content>
	</ItemGroup>

</Project>