using InsanityLib.Generators.Contexts;
using InsanityLib.Generators.Extensions;
using Microsoft.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Diagnostics;

namespace InsanityLib.Generators;

public sealed partial class ModSystemGenerator
{
    public void GenerateModSystemFile(SourceProductionContext context, GeneratorContext info)
    {
        var safeRoot = info.Root.Replace(".", string.Empty);
        
        var sw = new StringWriter();
        var writer = new IndentedTextWriter(sw, "    ");

        writer.WriteLine(
            """
            // <auto-generated/>
            using System;
            using System.Text;
            using System.Linq;
            using Newtonsoft.Json;
            using System.ComponentModel.Design;
            using System.Diagnostics.CodeAnalysis;
            using System.Collections.Generic;
            using Vintagestory.API.Client;
            using Vintagestory.API.Common;
            using Vintagestory.API.Server;
            using HarmonyLib;
            using InsanityLib.Extensions;
            using InsanityLib.Extended.AssetCategories;
            using InsanityLib.Auto.Config;

            #nullable enable
            """
        );

        var prefferedModSystemClassName = $"{safeRoot}ModSystem";
        info.ContainingType = info.Compilation.GetAllConcrete("Vintagestory.API.Common.ModSystem")
            .Where(SymbolExtensions.IsPartial)
            .OrderByDescending(symbol => symbol.Name == prefferedModSystemClassName)
            .ThenBy(SymbolExtensions.GetNamespaceDepth)
            .FirstOrDefault();
        
        var className = info.ContainingType?.Name ?? prefferedModSystemClassName;
        var classNamespace = info.ContainingType?.ContainingNamespace.ToDisplayString() ?? info.Root;

        writer.WriteLine();
        writer.WriteLine($"namespace {classNamespace};");
        writer.WriteLine();
        
        using(new BlockContext($"public partial class {className} : ModSystem").Use(writer))
        {
            writer.WriteLine();
            
            GenerateUtility(writer, info);

            GenerateServiceLogic(writer, info);

            GenerateAutoModConfigMethods(writer, info);

            GenerateStaticPatchCategoryList(writer, info);
            GenerateAutoPatcherMethod(writer, info);

            GenerateAssetCategoryMethods(writer, info);
            GenerateAutoRegistryMethod(writer, info);
            GenerateAutoNetworkMethod(writer, info);

            GenerateAutoSetupMethod(writer, info);
            GenerateAutoAssetsLoadedMethod(writer, info);

            GenerateAutoDisposeMethod(writer, info);
        }

        context.AddSource($"{className}.g.cs", sw.ToString());
    }
}