using InsanityLib.Generators.Contexts;
using InsanityLib.Generators.Extensions;
using Microsoft.CodeAnalysis;
using System.CodeDom.Compiler;

namespace InsanityLib.Generators;

public sealed partial class ModSystemGenerator
{
    public void GenerateModSystemFile(SourceProductionContext context, GeneratorContext info)
    {
       var safeRoot = info.Root.Replace(".", string.Empty);
        
        var sw = new StringWriter();
        var writer = new IndentedTextWriter(sw, "    ");

        writer.WriteLine(
            """
            // <auto-generated/>

            using System;
            using System.Linq;
            using System.ComponentModel.Design;
            using System.Diagnostics.CodeAnalysis;
            using Vintagestory.API.Client;
            using Vintagestory.API.Common;
            using Vintagestory.API.Server;
            using HarmonyLib;
            """
        );
        
        writer.WriteLine();
        writer.WriteLine($"namespace {info.Root};");
        writer.WriteLine();


        var modSystemClassName = $"{safeRoot}ModSystem"; //TODO have this auto bind to partial class if applicable
        using(new BlockContext($"public partial class {modSystemClassName} : ModSystem").Use(writer))
        {
            writer.WriteLine();
            
            GenerateServiceLogic(writer, info);

            GenerateStaticPatchCategoryList(writer, info);
            GenerateAutoPatcherMethod(writer, info);
            GenerateAutoRegistryMethod(writer, info);

            GenerateAutoSetupMethod(writer, info);

            GenerateAutoDisposeMethod(writer, info);
        }

        context.AddSource($"{modSystemClassName}.g.cs", sw.ToString());
    }
}